const videos={
 pent:{title:'Minor Pentatonic Scale — JustinGuitar',url:'https://www.youtube.com/watch?v=G-X1RemAzks',embed:'https://www.youtube-nocookie.com/embed/G-X1RemAzks',thumb:'https://i.ytimg.com/vi/G-X1RemAzks/hqdefault.jpg',source:'YouTube · JustinGuitar'},
 picking:{title:'Alternate picking com pentatônica — JustinGuitar',url:'https://www.youtube.com/watch?v=c0alXyaLTC4',embed:'https://www.youtube-nocookie.com/embed/c0alXyaLTC4',thumb:'https://i.ytimg.com/vi/c0alXyaLTC4/hqdefault.jpg',source:'YouTube · JustinGuitar'},
 blues:{title:'Essential Blues Lead Guitar',url:'https://www.justinguitar.com/modules/essential-blues-lead-guitar',source:'JustinGuitar · módulo com aulas em vídeo'},
 easy:{title:'Blues Guitar & Easy Improvisation',url:'https://www.justinguitar.com/modules/blues-guitar-easy-improvisation',source:'JustinGuitar · módulo com aulas em vídeo'},
 caged:{title:'CAGED System',url:'https://www.justinguitar.com/modules/caged-system',source:'JustinGuitar · módulo com aulas em vídeo'},
 scales:{title:'Scales & Modes',url:'https://www.justinguitar.com/classes/scales-modes',source:'JustinGuitar · curso com aulas em vídeo'},
 nps:{title:'Major Scale 3NPS',url:'https://www.justinguitar.com/modules/major-scale-3nps',source:'JustinGuitar · módulo com aulas em vídeo'},
 changes:{title:'Making The Blues Changes',url:'https://www.justinguitar.com/modules/making-the-blues-changes',source:'JustinGuitar · módulo com aulas em vídeo'}
};
const weeks=[
 ['Notas no braço: mapa prático',['Notas naturais na corda 6','Notas naturais na corda 5','Octavas: 6ª → 4ª e 5ª → 3ª','Encontre A, C, D, E e G no braço','Graus da pentatônica menor de A','Cante grau e toque nota','Boss: mapa de Am sem shape']],
 ['Pentatônica como linguagem',['Tônicas e notas de repouso','b3, 4 e 5: o que cada nota diz','b7 e tensão antes da resolução','Frases que começam em grau, não em shape','Pentatônica Am sobre pedal A','Pergunta–resposta com notas-alvo','Boss: solo de 12 compassos em Am']],
 ['Escala menor e harmonia',['Adicionar 2 e b6: menor natural','Comparar penta Am e menor natural','Notas fortes sobre Am','Notas fortes sobre G em Am natural','Notas fortes sobre F em Am natural','Progressão Am–G–F: trocar alvo','Boss: acompanhar Am–G–F']],
 ['Trocar junto com o acorde',['Triades maiores: A, G e F','Triades menores: Am, Em e Dm','Arpejo de Am dentro da penta','Arpejo de G dentro da escala','Guia de vozes: 3ª e 7ª','Progressão Am–G–F–E: nota por acorde','Boss: solo que segue os acordes']],
 ['Maior e menor por tonalidade',['Escala maior: graus e som','Relativa menor: C maior ↔ Am','Pentatônica maior aplicada','I–V–vi–IV em G: escala global','Acorde por acorde em G–D–Em–C','Mire a terça em cada mudança','Boss: pop progression em G']],
 ['CAGED aplicado ao solo',['CAGED: encontre a tônica em cada forma','Forma E: tríade e escala ao redor','Forma D: tríade e escala ao redor','Forma C: tríade e escala ao redor','Conectar duas formas em uma frase','CAGED sobre G–D–Em–C','Boss: navegação por CAGED']],
 ['Expansão do vocabulário',['3NPS para ver a escala maior','3NPS: conecte com CAGED','Sequências sem perder os graus','Escala maior sobre cada acorde diatônico','Pentatônica + notas de passagem','Misture arpejo, penta e escala','Boss: solo de 16 compassos']],
 ['Autonomia e performance',['Descubra a tonalidade por tônicas','Mapeie acordes antes de improvisar','Crie um mapa de notas-alvo','Improviso em Am–G–F–E','Improviso em G–D–Em–C','Grave, escute e corrija','Final Boss: solo que faz as mudanças']]
];
const kind=t=>/3NPS|Sequências/.test(t)?'nps':/CAGED|Forma [EDCAG]/.test(t)?'caged':/acorde|Acorde|Triades|Arpejo|Guia de vozes|nota por acorde|nota-alvo|alvo|mudança|mudanças/.test(t)?'changes':/Notas naturais|Octavas|Encontre|Graus|menor natural|Escala maior|Relativa|Pentatônica maior|diatônico|tonalidade|notas fortes|penta Am/.test(t)?'scales':/Grave|escute|mapa|Mapeie|Descubra|Crie/.test(t)?'easy':'pent';
const lessonData=weeks.flatMap(([week,titles],wi)=>titles.map((title,di)=>({id:wi*7+di+1,week:wi+1,day:di+1,title,kind:kind(title)})));
function content(l){const v=videos[l.kind];const key=l.week<=4?'A menor':l.week<=7?'G maior / E menor':'A menor e G maior';const focus={pent:'as cinco notas da pentatônica menor e a tônica A',picking:'articulação sincronizada entre as duas mãos',caged:'formas de acorde e tônicas do sistema CAGED',changes:'relação entre escala, acorde e nota-alvo',scales:'função dos graus da escala e escolha por ouvido',nps:'três notas por corda, palhetada e economia de movimento',easy:'frases curtas, ritmo, pausa e intenção'}[l.kind];let specific={
 'Notas naturais na corda 6':'Fale as notas naturais em voz alta da corda solta até a 12ª casa; use os sustenidos apenas como casas entre elas.',
 'Notas naturais na corda 5':'Localize A, C, D, E e G na corda 5 sem olhar um diagrama; confira tocando depois.',
 'Octavas: 6ª → 4ª e 5ª → 3ª':'Escolha uma nota na 6ª/5ª corda e ache sua oitava duas cordas abaixo e duas casas acima; faça o caminho inverso.',
 'Encontre A, C, D, E e G no braço':'Use um cronômetro de 60 segundos: encontre cada nota em todas as cordas, diga o nome e toque-a limpa.',
 'Graus da pentatônica menor de A':'Sobre Am, diga 1, b3, 4, 5, b7 ao tocar A, C, D, E, G. Ouvir grau é mais útil do que decorar desenho.',
 'Cante grau e toque nota':'Cante “1–b3–4–5–b7”, pare em um grau escolhido ao acaso e encontre-o em duas regiões do braço.',
 'Tônicas e notas de repouso':'Improvise duas notas por compasso e termine cada frase em A; depois termine em C e compare a cor.',
 'b3, 4 e 5: o que cada nota diz':'Faça três frases, cada uma pousando em C, D e E. Descreva qual delas soa mais estável sobre Am.',
 'b7 e tensão antes da resolução':'Toque G e resolva para A usando apenas uma nota por pulso; mantenha o silêncio depois da resolução.',
 'Frases que começam em grau, não em shape':'Escolha b3, 4 ou 5 como início; encontre-o antes de tocar e construa uma frase de quatro notas.',
 'Adicionar 2 e b6: menor natural':'Compare a pentatônica Am (A C D E G) com a menor natural (A B C D E F G); toque B e F como cores, não como corrida.',
 'Comparar penta Am e menor natural':'Sobre um pedal Am, grave quatro compassos só de penta e quatro incluindo B/F; circule a nota que mais gostou.',
 'Notas fortes sobre G em Am natural':'Sobre G maior, mire B (3ª) ou D (5ª) enquanto usa as mesmas notas de A menor natural ao redor.',
 'Notas fortes sobre F em Am natural':'Sobre F maior, mire A (3ª) ou C (5ª); resolva nelas no primeiro pulso do novo acorde.',
 'Progressão Am–G–F: trocar alvo':'Mantenha a escala A menor natural. Quando o acorde mudar, faça a próxima frase cair em A/C/E, depois B/D/G, depois A/C/F.',
 'Triades maiores: A, G e F':'Toque 1–3–5 de A, G e F em três grupos de cordas. Nomeie cada nota antes de palhetar.',
 'Triades menores: Am, Em e Dm':'Toque 1–b3–5 de Am, Em e Dm e encontre uma inversão próxima da posição atual.',
 'Guia de vozes: 3ª e 7ª':'Em cada troca, mova a menor distância possível para a 3ª do próximo acorde; deixe o resto da frase responder.',
 'Progressão Am–G–F–E: nota por acorde':'Use A menor harmônica somente sobre E maior para evidenciar G#; nos demais, use A menor natural. Ouça a diferença.',
 'Escala maior: graus e som':'Em G maior, fale 1–2–3–4–5–6–7 enquanto toca G A B C D E F#. Resolva de F# para G.',
 'Relativa menor: C maior ↔ Am':'Toque a mesma coleção de notas e alterne a tônica de repouso: C para som maior, A para som menor.',
 'I–V–vi–IV em G: escala global':'Sobre G–D–Em–C, mantenha G maior. A mudança acontece ao mirar G/B/D, D/F#/A, E/G/B e C/E/G.',
 'Acorde por acorde em G–D–Em–C':'No primeiro pulso de cada acorde, toque sua 3ª: B, F#, G, E. Complete o compasso com notas vizinhas da escala.',
 'Mire a terça em cada mudança':'Cante a 3ª do próximo acorde antes da mudança e então encontre a versão mais perto de sua mão.',
 'CAGED: encontre a tônica em cada forma':'Escolha G e localize suas tônicas através das cinco formas CAGED; toque uma tríade ao redor de cada uma.',
 'Conectar duas formas em uma frase':'Comece uma frase na forma E e termine em uma tríade vizinha da forma D; não corra pelo desenho inteiro.',
 'CAGED sobre G–D–Em–C':'Para cada acorde, encontre a forma CAGED mais próxima e seu 1–3–5. Improvise no espaço de quatro casas.',
 '3NPS para ver a escala maior':'Toque G maior em 3NPS e pare em cada G, B e D; conecte a sequência ao CAGED, não apenas à digitação.',
 '3NPS: conecte com CAGED':'Em uma região do braço, ache a tríade de G e as notas 3NPS imediatamente ao redor dela.',
 'Escala maior sobre cada acorde diatônico':'Use uma única escala de G maior, mas faça seu primeiro ou último som ser nota do acorde presente.',
 'Pentatônica + notas de passagem':'Comece com uma frase de pentatônica maior de G e adicione F# ou C como passagem para uma nota-alvo.',
 'Improviso em Am–G–F–E':'Planeje uma nota de chegada para cada acorde: C/A, B/D, A/C e G#. Grave sem parar por dois loops.',
 'Improviso em G–D–Em–C':'Antes de tocar, escreva as tríades. Depois improvise limitando-se a três notas por acorde no primeiro loop.',
 'Final Boss: solo que faz as mudanças':'Escolha uma progressão, marque 1–3–5 de cada acorde em duas áreas do braço e grave 32 compassos resolvendo cada troca.',
'Mapa da pentatônica Am — box 1':'Toque o desenho na 5ª casa sem decorar por números: diga “A, C, D, E, G” enquanto sobe.',
'Tônicas e graus dentro do box 1':'Pare em cada A do box; toque a nota e cante antes de continuar.',
'Primeiro bend afinado':'Compare o bend da corda G com a nota de destino na corda B antes de dobrar a corda.',
'Vibrato controlado':'Sustente a tônica A por quatro pulsos e mova a corda de forma regular, não aleatória.',
'Nota blue: b5 com intenção':'Toque a b5 apenas como passagem entre 4 e 5; resolva em uma nota estável.',
'Mirar a terça do acorde':'Quando o acorde mudar, encontre primeiro sua terça e então responda com uma frase curta.',
'Motivo e variação':'Crie uma célula de três notas; repita-a mudando somente o final ou o ritmo.',
'Transcrever 2 compassos':'Ouça duas vezes sem instrumento, cante o ritmo e só então procure as notas.',
'Gravar e avaliar o solo':'Grave uma tomada sem parar; anote um ponto de ritmo e um de afinação para ajustar.',
'Final Boss: solo completo':'Grave um solo de 32 compassos: introdução simples, desenvolvimento, clímax e final na tônica.'}[l.title]||`Pratique ${l.title.toLowerCase()} em blocos de duas repetições perfeitas; pare, corrija e recomece sem acelerar.`;
return {v,objective:`Aplicar ${l.title.toLowerCase()} em uma improvisação curta, consciente e musical.`,prereq:l.id===1?'Guitarra afinada, palheta e 30 minutos sem interrupções.':`Conclua a Aula ${l.id-1} e toque o exercício anterior a 70% do BPM sem travar.`,concept:`O foco de hoje é ${focus}. Em vez de percorrer desenhos automaticamente, ouça cada resolução e mantenha a pulsação. A tonalidade de referência é ${key}.`,timeline:['0–3 min — afine, ajuste o BPM e toque a tônica A em cada registro.','3–8 min — aqueça lentamente, com movimentos pequenos e sem tensão no polegar.',`8–15 min — estude o núcleo: ${specific}`,'15–22 min — repita o exercício em semínimas, colcheias e com uma pausa a cada frase.','22–27 min — improvise sobre o backing track: uma frase de 2 compassos, 2 compassos de silêncio.','27–30 min — grave uma tomada; ouça e escolha uma melhoria concreta para amanhã.'],exercises:[specific,'Toque o material em três BPMs: 60, 70 e 80. Só suba quando houver duas passagens limpas seguidas.','Crie uma frase que termine em A e uma que evite A; compare a sensação de repouso.'],mistakes:['Acelerar quando surge uma nota difícil; reduza o BPM e preserve o pulso.','Tocar todas as notas com o mesmo volume; escolha uma nota de chegada e deixe-a cantar.','Confundir prática de forma com improviso: primeiro toque limpo, depois faça música com espaço.'],criteria:`Considere concluída quando executar o exercício a 80 BPM (ou seu máximo limpo), identificar a tônica A e gravar uma frase de 8 compassos usando o foco da aula pelo menos três vezes.`,mission:`Missão ${String(l.id).padStart(2,'0')}: faça uma tomada de 60 segundos. Use ${l.title.toLowerCase()} em pelo menos três frases e marque a melhor como seu “take do dia”.`,backing:`Procure no YouTube: “${key} ${l.kind==='changes'?'blues':'backing track'} ${l.kind==='nps'?'rock 100 bpm':'80 bpm'}”. Ou use um loop de Am a ${70+l.week*5} BPM.`}}
let state=JSON.parse(localStorage.getItem('giq-v2')||'{"done":[],"xp":0,"last":""}');let active=1,timerId,seconds=1800,audio;
const $=s=>document.querySelector(s);const esc=s=>s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem('giq-v2',JSON.stringify(state))}function renderNav(){let current=lessonData.find(x=>x.id===active);$('#weekTabs').innerHTML=weeks.map((w,i)=>`<button class="${i+1===current.week?'active':''}" onclick="showWeek(${i+1})">Semana ${i+1}</button>`).join('');$('#lessonList').innerHTML=lessonData.filter(x=>x.week===current.week).map(x=>`<button class="lesson-item ${x.id===active?'active':''} ${state.done.includes(x.id)?'done':''}" onclick="openLesson(${x.id})"><i class="check"></i><span><b>${x.id}. ${esc(x.title)}</b><small>Aula ${x.day} · ${state.done.includes(x.id)?'concluída':'em aberto'}</small></span></button>`).join('');let n=state.done.length;$('#progressText').textContent=`${n} / 56 aulas`;$('#progressBar').style.width=`${n/56*100}%`;$('#xp').textContent=state.xp;$('#level').textContent=`Nível ${Math.floor(state.xp/350)+1}`;$('#streak').textContent=state.last===new Date().toDateString()?1:0}
function renderLesson(){let l=lessonData.find(x=>x.id===active),d=content(l),v=d.v,thumb=v.thumb||'https://www.justinguitar.com/assets/images/logo.svg';$('#lesson').innerHTML=`<p class="lesson-kicker">SEMANA ${l.week} · AULA ${l.day} · ${state.done.includes(l.id)?'✓ CONCLUÍDA':'MISSÃO ATIVA'}</p><h2>${l.id}. ${esc(l.title)}</h2><div class="video"><img src="${thumb}" alt="Capa do recurso ${esc(v.title)}" onerror="this.style.display='none'"><div><p class="eyebrow">VÍDEO / AULA DE REFERÊNCIA</p><h3>${esc(v.title)}</h3><p class="muted">${v.source}. Este recurso foi selecionado para o tema desta aula.</p><a href="${v.url}" target="_blank" rel="noopener">Abrir vídeo/aula ↗</a></div></div><div class="sections"><article class="section"><h3>Objetivo</h3><p>${d.objective}</p></article><article class="section"><h3>Pré-requisito</h3><p>${d.prereq}</p></article><article class="section wide"><h3>Conceito</h3><p>${d.concept}</p></article><article class="section wide"><h3>Roteiro minuto a minuto</h3><ol>${d.timeline.map(x=>`<li>${x}</li>`).join('')}</ol></article><article class="section"><h3>Exercícios específicos</h3><ul>${d.exercises.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="section"><h3>Erros comuns</h3><ul>${d.mistakes.map(x=>`<li>${x}</li>`).join('')}</ul></article><article class="section"><h3>Critério de conclusão</h3><p>${d.criteria}</p></article><article class="section"><h3>Backing track</h3><p>${d.backing}</p></article><article class="section wide"><h3>Missão</h3><p>${d.mission}</p></article></div><button class="complete" onclick="toggleDone(${l.id})">${state.done.includes(l.id)?'↩ Desmarcar aula':'✓ Concluir aula (+100 XP)'}</button>`}
window.openLesson=id=>{active=id;renderNav();renderLesson();scrollTo({top:0,behavior:'smooth'})};window.showWeek=w=>{active=lessonData.find(x=>x.week===w).id;renderNav();renderLesson()};window.toggleDone=id=>{if(state.done.includes(id)){state.done=state.done.filter(x=>x!==id);state.xp=Math.max(0,state.xp-100)}else{state.done.push(id);state.xp+=100;state.last=new Date().toDateString()}save();renderNav();renderLesson()};
function tick(){seconds--;if(seconds<0){clearInterval(timerId);timerId=null;seconds=0}$('#timer').textContent=`⏱ ${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`};$('#timer').onclick=()=>{if(timerId){clearInterval(timerId);timerId=null}else timerId=setInterval(tick,1000)};$('#metro').onclick=()=>{let bpm=+$('#bpm').value;if(audio)clearInterval(audio);let ctx=new AudioContext();audio=setInterval(()=>{let o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.08,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.05);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.06)},60000/bpm);setTimeout(()=>{clearInterval(audio);audio=null;ctx.close()},30000)};
const notes=['E','F','F#','G','G#','A','A#','B','C','C#','D','D#'],tuning=[4,11,7,2,9,4];let layer='roots';function fret(){let allowed=layer==='roots'?['A']:layer==='penta'?['A','C','D','E','G']:layer==='minor'?['A','B','C','D','E','F','G']:notes;$('#fretboard').innerHTML=tuning.map((open,s)=>`<div class="string">${Array.from({length:13},(_,f)=>{let n=notes[(open+f)%12];return `<button class="note ${allowed.includes(n)?'marked':''}" title="Corda ${6-s}, casa ${f}">${n}</button>`}).join('')}</div>`).join('');document.querySelectorAll('.note').forEach(b=>b.onclick=()=>b.classList.toggle('selected'))}document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{layer=b.dataset.layer;fret()});
const qs=[['Qual grau dá o som “blue” na escala blues?',['b5','7M','2M'],0],['Qual nota é a tônica de Am?',['A','C','E'],0],['O que melhora uma frase?', ['Pausa e ritmo','Mais notas','Mais velocidade'],0]];let qi=0;function quiz(){let q=qs[qi];$('#quizQuestion').textContent=q[0];$('#quizChoices').innerHTML=q[1].map((a,i)=>`<button onclick="answer(${i})">${a}</button>`).join('');$('#quizFeedback').textContent=''}window.answer=i=>{let q=qs[qi];$('#quizFeedback').textContent=i===q[2]?'✓ Certo — +20 XP!':'Ainda não. Ouça e tente de novo.';if(i===q[2]){state.xp+=20;save();renderNav();qi=(qi+1)%qs.length;setTimeout(quiz,700)}};renderNav();renderLesson();fret();quiz();
