# -*- coding: utf-8 -*-
# Gerador do lessons.json — Fase 1 (Aulas 1-15)
import json

course = {
    "id": "guitar-improvisation-quest",
    "title": "Guitar Improvisation Quest",
    "version": "3.0",
    "language": "pt-BR",
    "phase": 1,
    "phaseTitle": "Fase 1: Pentatônica Menor + CAGED + Intervalos",
    "totalLessons": 80,
    "totalPhases": 8,
    "implementedLessons": 15,
}

SCALE = {"name": "A minor pentatonic", "formula": ["1", "b3", "4", "5", "b7"], "notes": ["A", "C", "D", "E", "G"]}
CHORD = {"name": "Am", "notes": ["A", "C", "E"], "formula": ["1", "b3", "5"]}
BT = {"title": "Backing track em A menor", "url": None, "type": "search-required"}
XP = {"know": 25, "play": 50, "use": 100}

L = []

L.append({
    "id": 1, "week": 1, "day": 1, "phase": 1,
    "title": "Shape 1 + CAGED: o acorde dentro da pentatônica",
    "subtitle": "Am como âncora harmônica do Shape 1 na 5ª casa",
    "objective": "Relacionar o Shape 1 da pentatônica menor de Am com o acorde Am (forma CAGED) da mesma região, enxergando 1, b3 e 5 como o esqueleto harmônico.",
    "prerequisite": "Guitarra afinada e o Shape 1 da pentatônica menor já tocado de forma mecânica (não precisa dominar intervalos).",
    "concept": "Você já toca o Shape 1 de cor. Agora vamos transformá-lo em mapa: o acorde Am (A, C, E) está dentro do Shape 1. A nota A é a tônica (1), C é a terça menor (b3) e E é a quinta justa (5). Essas três notas — os chord tones — são o esqueleto do acorde e o ponto de repouso de qualquer frase. Quando você enxerga o acorde dentro da escala, deixa de correr o desenho e passa a escolher notas com sentido.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma E (Em) — Am na 5ª casa",
    "whatToSee": [
        "O acorde Am (A, C, E) barrado na 5ª casa (forma E).",
        "As três tônicas A: 6ª corda casa 5, 4ª corda casa 7 e 1ª corda casa 5.",
        "As terças menores C: 3ª corda casa 5, 1ª corda casa 8 e 6ª corda casa 8.",
        "As quintas E: 5ª corda casa 7 e 2ª corda casa 5.",
        "Que os chord tones (1, b3, 5) são exatamente as notas do acorde.",
    ],
    "chordScaleRelation": "O acorde Am (A, C, E) usa as notas 1, b3 e 5 da pentatônica. O Shape 1 é o acorde Am aberto ao redor: 4 (D) e b7 (G) aparecem como tensões entre os chord tones.",
    "fretboard": {
        "shape": 1, "position": 5, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--1(5)-----b3(8)--\nB|--5(5)-----b7(8)--\nG|--b3(5)----4(7)---\nD|--b7(5)----1(7)---\nA|--4(5)-----5(7)---\nE|--1(5)-----b3(8)--",
        "tab": "e|--------------5-|\nB|------------5---|\nG|----------5-----|\nD|--------7-------|\nA|------7---------|\nE|----5-----------|",
    },
    "exercises": [
        "Tocar o acorde Am (forma E, 5ª casa) e sustentar cada nota separadamente, nomeando-as: A, E, A, C, E, A.",
        "Observar o acorde no braço e localizar todas as tônicas A (6ª casa 5, 4ª casa 7, 1ª casa 5).",
        "Localizar todas as terças menores C (3ª casa 5, 1ª casa 8, 6ª casa 8).",
        "Localizar todas as quintas E (5ª casa 7, 2ª casa 5).",
        "Tocar somente 1, b3 e 5 em qualquer ordem, falando o nome do intervalo em voz alta enquanto toca.",
    ],
    "earTraining": {"instruction": "Toque A (6ª corda casa 5) e cante Um. Toque C (3ª corda casa 5) e cante Terça menor — sinta a cor triste do menor. Toque E (5ª corda casa 7) e cante Quinta — sinta a estabilidade neutra. Repita o ciclo 1 → b3 → 5 até memorizar cada sensação."},
    "improvisation": {"instruction": "Com backing track em A menor (75 BPM), improvise por 5 minutos usando apenas as notas do Shape 1. Regra obrigatória: toda frase deve terminar em A, C ou E (chord tones). Se a frase terminar em outra nota, considere que ela ficou no ar e recomece."},
    "theoryRoutine": [
        "00–05 min: Tocar o acorde Am e verbalizar A, C, E como 1, b3 e 5.",
        "05–15 min: Localizar e tocar tônicas, terças menores e quintas no Shape 1.",
        "15–25 min: Treino de ouvido 1 → b3 → 5 com canto.",
        "25–30 min: Improvisar terminando todas as frases em chord tone.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Alternate picking e sincronização limpa no Shape 1",
        "routine": [
            "00–08 min: Aquecimento com o Shape 1 ascendente e descendente a 60 BPM em colcheias.",
            "08–18 min: Arpejo do acorde Am (1, b3, 5) com palhetada alternada a 70 BPM.",
            "18–26 min: Sincronização mão esquerda/direita na troca entre cordas adjacentes.",
            "26–30 min: Rodar o Shape 1 a 80 BPM mantendo o som limpo.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "The CAGED System", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/modules/caged-system", "reason": "Mapa dos shapes de acorde que servem de âncora visual para localizar Am em cada região do braço."},
    "commonMistakes": [
        "Correr o desenho do Shape 1 sem saber qual nota é chord tone e qual é tensão.",
        "Terminar frases em D (4) ou G (b7) sem perceber que ficou no ar.",
        "Não verbalizar o intervalo ao tocar, mantendo o conhecimento só visual.",
    ],
    "mastery": {
        "know": "Sei que Am = A, C, E e que esses são os graus 1, b3 e 5 da pentatônica.",
        "play": "Consigo localizar e tocar 1, b3 e 5 no Shape 1 sem hesitar.",
        "use": "Consigo terminar frases conscientemente em A, C ou E sobre o backing track.",
    },
    "review": [],
    "challenge": "Grave 1 minuto improvisando e marque: quantas frases terminaram em chord tone? Se menos de 80%, repita o exercício.",
    "mission": "Gravar um áudio curto tocando o acorde Am e depois arpejando 1, b3 e 5, nomeando cada intervalo.",
    "xp": XP,
})

L.append({
    "id": 2, "week": 1, "day": 2, "phase": 1,
    "title": "Shape 1 completo: 4 e b7 como tensão",
    "subtitle": "O mapa inteiro do Shape 1: 1, b3, 4, 5 e b7",
    "objective": "Completar o Shape 1 adicionando a quarta justa (4) e a sétima menor (b7), diferenciando claramente chord tones de tensões.",
    "prerequisite": "Aula 1: localizar 1, b3 e 5 no Shape 1.",
    "concept": "A pentatônica menor tem 5 forças: 1 (repouso supremo), 5 (forte consonância), b3 (identidade menor), 4 (tensão que quer descer) e b7 (tensão/cor que quer subir). As tensões 4 e b7 não são notas do acorde Am, mas vivem ao redor dele e criam movimento. A regra de ouro: 4 resolve em b3, e b7 resolve em 1. Ao dominar essas duas gravidades, suas frases ganham direção.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma E (Em) — Am na 5ª casa",
    "whatToSee": [
        "O mapa completo: 1, b3, 4, 5 e b7 no Shape 1.",
        "As quartas D: 5ª corda casa 5 e 3ª corda casa 7.",
        "As sétimas menores G: 4ª corda casa 5 e 2ª corda casa 8.",
        "A vizinhança: 4 (D) fica ao lado do b3 (C), e b7 (G) fica ao lado da tônica (A).",
    ],
    "chordScaleRelation": "Chord tones = 1, b3, 5 (repouso). Tensões = 4 e b7 (movimento). Toda a melodia do Shape 1 gira entre esses dois polos: repousar no acorde e tensionar fora dele.",
    "fretboard": {
        "shape": 1, "position": 5, "highlight": ["1", "b3", "4", "5", "b7"],
        "intervalMap": "e|--1(5)-----b3(8)--\nB|--5(5)-----b7(8)--\nG|--b3(5)----4(7)---\nD|--b7(5)----1(7)---\nA|--4(5)-----5(7)---\nE|--1(5)-----b3(8)--",
        "tab": "e|------------------5-8-|\nB|--------------5-8-----|\nG|----------5-7---------|\nD|------5-7-------------|\nA|--5-7-----------------|\nE|--5-8-----------------|",
    },
    "exercises": [
        "Localizar todas as 4 (D): 5ª casa 5 e 3ª casa 7.",
        "Localizar todas as b7 (G): 4ª casa 5 e 2ª casa 8.",
        "Tocar 4 → b3 (D → C) e sentir a gravidade de descida.",
        "Tocar b7 → 1 (G → A) e sentir a gravidade de subida.",
        "Tocar 5 → 1 (E → A) e sentir a resolução de repouso secundário.",
    ],
    "earTraining": {"instruction": "Toque D (5ª corda casa 5) e cante Quatro — sinta a suspensão. Toque C (3ª corda casa 5) e cante Terça menor — sinta a chegada. Depois toque G (4ª corda casa 5) e cante Sétima — sinta a cor aberta — e resolva em A (4ª corda casa 7) cantando Um."},
    "improvisation": {"instruction": "Sobre backing track em A menor, improvise usando as 5 notas. Obrigação: usar pelo menos uma resolução 4 → b3 e uma resolução b7 → 1 a cada 4 frases. As demais frases podem terminar em chord tone."},
    "theoryRoutine": [
        "00–05 min: Revisar 1, b3 e 5 e adicionar 4 e b7 no Shape 1.",
        "05–15 min: Exercícios de localização de 4 e b7.",
        "15–25 min: Resoluções 4 → b3 e b7 → 1 com canto.",
        "25–30 min: Improvisar com as resoluções obrigatórias.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Controle de dinâmica e palhetada nas resoluções",
        "routine": [
            "00–08 min: Shape 1 completo em colcheias a 65 BPM.",
            "08–18 min: Células 4 → b3 e b7 → 1 com acento na nota de chegada.",
            "18–26 min: Alternância de palhetada descendente/ascendente com foco na nota-alvo.",
            "26–30 min: Frase completa a 80 BPM com respiração entre as ideias.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Intervals On The Guitar Neck", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/intervals-on-the-guitar-neck-et-098", "reason": "Ensina a enxergar intervalos no braço em vez de decorar desenhos."},
    "commonMistakes": [
        "Tratar 4 e b7 como notas de repouso em vez de tensão.",
        "Resolver 4 → 5 em vez de 4 → b3, perdendo a gravidade natural do menor.",
        "Não ouvir a diferença entre consonância (1, 5) e tensão (4, b7).",
    ],
    "mastery": {
        "know": "Sei que 1, b3 e 5 são chord tones (repouso) e que 4 e b7 são tensões.",
        "play": "Consigo localizar 4 e b7 e executar 4 → b3 e b7 → 1 limpos.",
        "use": "Consigo inserir tensão e resolução conscientemente nas frases.",
    },
    "review": ["Localizar 1, b3 e 5 no Shape 1 (Aula 1)."],
    "challenge": "Crie 4 frases: uma terminando em 1, uma em b3, uma usando 4 → b3 e uma usando b7 → 1.",
    "mission": "Gravar as 4 frases do desafio e ouvir de volta, confirmando as resoluções.",
    "xp": XP,
})

L.append({
    "id": 3, "week": 1, "day": 3, "phase": 1,
    "title": "Shape 1 musical: intervalos viram frases",
    "subtitle": "Transformar o mapa do Shape 1 em linguagem musical",
    "objective": "Transformar os intervalos do Shape 1 em linguagem musical, usando silêncio, bends e vibrato com nota-alvo consciente.",
    "prerequisite": "Aulas 1 e 2: mapa completo do Shape 1 com chord tones e tensões.",
    "concept": "Intervalo é informação, mas música é intenção. Agora você vai escolher onde cada frase termina: em 1 (repouso definitivo), em b3 (cor menor) ou em 5 (repouso aberto), criando tensão em 4 ou b7 e resolvendo. O silêncio é o que separa uma frase da outra e dá respiração. O bend deve sempre ter uma nota-alvo — você dobra sabendo para qual grau vai. O vibrato dá vida à nota de chegada, nunca à nota de passagem.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma E (Em) — Am na 5ª casa",
    "whatToSee": [
        "As notas de chegada: 1 (A), b3 (C) e 5 (E) no Shape 1.",
        "As notas de tensão: 4 (D) e b7 (G) para criar movimento.",
        "O silêncio como parte do fraseado, não como falha.",
        "O bend de D (4) subindo para E (5) e de G (b7) subindo para A (1).",
    ],
    "chordScaleRelation": "A melodia nasce quando a tensão (4, b7) caminha para o repouso (1, b3, 5). O acorde Am é o porto; as tensões são as ondas que voltam para ele.",
    "fretboard": {
        "shape": 1, "position": 5, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--1(5)-----b3(8)--\nB|--5(5)-----b7(8)--\nG|--b3(5)----4(7)---\nD|--b7(5)----1(7)---\nA|--4(5)-----5(7)---\nE|--1(5)-----b3(8)--",
        "tab": "e|----------------------|\nB|----------------------|\nG|------5---------------|\nD|----------5---7-------|\nA|--5-------------------|\nE|----------------------|",
    },
    "exercises": [
        "Frase terminando em 1 (A): toque D (4) → C (b3) → A (1).",
        "Frase terminando em b3 (C): toque G (b7) → E (5) → C (b3).",
        "Frase terminando em 5 (E): toque A (1) → G (b7) → E (5).",
        "Frase criando tensão em 4 (D) e resolvendo: sustente o D e depois desça para C (b3).",
        "Frase criando tensão em b7 (G) e resolvendo: sustente o G e depois suba para A (1).",
        "Bend com nota-alvo: dobre D (4) na 3ª corda casa 7 até E (5) e sustente com vibrato.",
    ],
    "earTraining": {"instruction": "Cante mentalmente a nota-alvo antes de tocá-la: escolha terminar em 1, cante Um, e só então toque a nota. Repita para b3 e 5. Esse exercício liga o ouvido ao braço."},
    "improvisation": {"instruction": "Improvisar 2 minutos livres no Shape 1. Depois 2 minutos em que toda tensão (4 ou b7) precisa ser resolvida antes do fim da frase. Use silêncio entre as frases e vibrato apenas na nota de chegada."},
    "theoryRoutine": [
        "00–08 min: Frases com terminação em 1, b3 e 5.",
        "08–16 min: Tensão em 4 e b7 com resolução.",
        "16–24 min: Bend com nota-alvo e vibrato na chegada.",
        "24–30 min: Improvisação com silêncio e resolução obrigatória.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Bends, vibrato e silêncio rítmico",
        "routine": [
            "00–08 min: Bend de meio tom (4 → b3) e de tom inteiro (b7 → 1) com afinação.",
            "08–18 min: Vibrato controlado na nota de chegada (largo e depois apertado).",
            "18–26 min: Frases com pausas de 1 e 2 tempos, mantendo o metrônomo.",
            "26–30 min: Ligar bend → vibrato → silêncio em uma frase completa.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Introduction to Vibrato Techniques", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/introduction-to-vibrato-techniques-bg-2103", "reason": "Fundamento de musicalidade para dar vida às notas de chegada do Shape 1."},
    "commonMistakes": [
        "Fazer bend sem saber a nota-alvo, dobrando ao acaso.",
        "Vibrar a nota de passagem em vez da nota de chegada.",
        "Emendar frases sem silêncio, perdendo a respiração musical.",
    ],
    "mastery": {
        "know": "Entendo como silêncio, bend e vibrato transformam intervalos em frases.",
        "play": "Consigo executar bends com nota-alvo e vibrato limpo na chegada.",
        "use": "Consigo improvisar com intenção, resolvendo tensões e respirando entre frases.",
    },
    "review": ["Chord tones e tensões do Shape 1 (Aula 2).", "Resoluções 4 → b3 e b7 → 1 (Aula 2)."],
    "challenge": "Grave 2 minutos livres e 2 minutos com resolução obrigatória, e compare a sensação de intenção.",
    "mission": "Criar 3 frases curtas que soem musicais, cada uma com silêncio antes e depois.",
    "xp": XP,
})

L.append({
    "id": 4, "week": 1, "day": 4, "phase": 1,
    "title": "Shape 2 + CAGED: nova região, mesmo mapa",
    "subtitle": "Shape 2 na região 7–10, ancorado no acorde Am (forma D)",
    "objective": "Introduzir o Shape 2 sem abandonar o Shape 1, ancorando 1, b3 e 5 na região 7–10 e reconhecendo o acorde Am (forma D) ali dentro.",
    "prerequisite": "Shapes 1 (Aulas 1 a 3) com 1, b3 e 5 localizados com segurança.",
    "concept": "O Shape 2 vive na região das casas 7 a 10. A tônica A está na 4ª corda casa 7 e na 2ª corda casa 10; a terça menor C na 1ª e 6ª cordas casa 8 e na 4ª corda casa 10; a quinta E na 5ª corda casa 7 e na 3ª corda casa 9. O acorde Am (forma D) usa exatamente essas notas: A, C e E. Você não está decorando um desenho novo — está reconhecendo o mesmo acorde em outra região. Distribua o estudo em 70% Shape 2, 20% revisão do Shape 1 e 10% teste aleatório.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma D (Dm) — Am na região 7–10",
    "whatToSee": [
        "O acorde Am (forma D): 4ª corda casa 7 (A), 3ª corda casa 9 (E), 2ª corda casa 10 (A) e 1ª corda casa 8 (C).",
        "As tônicas A: 4ª corda casa 7 e 2ª corda casa 10.",
        "As terças menores C: 1ª corda casa 8, 6ª corda casa 8 e 4ª corda casa 10.",
        "As quintas E: 5ª corda casa 7 e 3ª corda casa 9.",
    ],
    "chordScaleRelation": "O Shape 2 é o acorde Am (forma D) aberto ao redor. As notas do acorde (1, b3, 5) são os alvos; as tensões 4 (D) e b7 (G) preenchem o espaço entre elas.",
    "fretboard": {
        "shape": 2, "position": 7, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--b3(8)----4(10)--\nB|--b7(8)----1(10)--\nG|--4(7)-----5(9)---\nD|--1(7)-----b3(10)-\nA|--5(7)-----b7(10)-\nE|--b3(8)----4(10)--",
        "tab": "e|--------8-|\nB|------10--|\nG|----9-----|\nD|--7-------|\nA|----------|\nE|----------|",
    },
    "exercises": [
        "Tocar o acorde Am (forma D) e nomear as notas: A, E, A, C.",
        "Localizar todas as tônicas 1 (A) no Shape 2.",
        "Localizar todas as terças menores b3 (C) no Shape 2.",
        "Localizar todas as quintas 5 (E) no Shape 2.",
        "Improvisação curta de 1 minuto usando só 1, b3 e 5 no Shape 2.",
        "Teste aleatório: feche os olhos e toque, sob comando, 1, b3 ou 5 em lugares diferentes do Shape 2.",
    ],
    "earTraining": {"instruction": "Toque a tônica A (4ª corda casa 7) e cante Um. Toque C (4ª corda casa 10) e cante Terça menor. Toque E (3ª corda casa 9) e cante Quinta. Perceba que a sensação é a mesma do Shape 1 — só mudou a posição."},
    "improvisation": {"instruction": "Com backing track em A menor, improvise 70% do tempo no Shape 2 e 20% no Shape 1. Toda frase deve terminar em 1, b3 ou 5. Nos 10% finais, alterne regiões de forma aleatória."},
    "theoryRoutine": [
        "00–10 min: Acorde Am (forma D) e localização de 1, b3, 5 no Shape 2.",
        "10–20 min: Revisão do Shape 1 (1, b3, 5).",
        "20–27 min: Improvisação 70/20 nos dois shapes.",
        "27–30 min: Teste aleatório de localização.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Mudança de posição e sincronização no Shape 2",
        "routine": [
            "00–08 min: Shape 2 em colcheias a 60 BPM.",
            "08–18 min: Arpejo do acorde Am (forma D) com palhetada alternada.",
            "18–26 min: Alternar Shape 1 e Shape 2 a cada 4 compassos.",
            "26–30 min: Rodar o Shape 2 a 75 BPM com som limpo.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Minor Pentatonic: Essential Information", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/minor-pentatonic-essential-information-sc-301", "reason": "Revisa a teoria dos shapes e prepara a transição para o Shape 2."},
    "commonMistakes": [
        "Abandonar o Shape 1 por completo ao estudar o Shape 2.",
        "Tratar o Shape 2 como desenho novo em vez de reconhecer o mesmo acorde Am.",
        "Perder a referência da tônica A ao se mover para a região 7–10.",
    ],
    "mastery": {
        "know": "Sei que o Shape 2 é o mesmo Am (A, C, E) na região 7–10 (forma D).",
        "play": "Consigo localizar e tocar 1, b3 e 5 no Shape 2 sem hesitar.",
        "use": "Consigo alternar Shape 1 e Shape 2 terminando frases em chord tone.",
    },
    "review": ["Shape 1: localizar 1, b3 e 5 (Aula 1).", "Resoluções 4 → b3 e b7 → 1 (Aula 2)."],
    "challenge": "Toque uma frase no Shape 1 e repita a mesma ideia (mesmos intervalos) no Shape 2.",
    "mission": "Gravar a mesma frase nos dois shapes e comparar a orientação.",
    "xp": XP,
})

L.append({
    "id": 5, "week": 1, "day": 5, "phase": 1,
    "title": "Shape 2 completo: 4 e b7 + randomização",
    "subtitle": "Adicionando tensões ao Shape 2 e misturando os shapes",
    "objective": "Completar o Shape 2 com 4 e b7, e treinar randomização de intervalo alternando entre Shape 1 e Shape 2.",
    "prerequisite": "Aula 4: 1, b3 e 5 no Shape 2.",
    "concept": "O Shape 2 também tem suas quartas (4 = D) e sétimas menores (b7 = G). No Shape 2: 4 (D) está na 6ª corda casa 10, na 3ª corda casa 7 e na 1ª corda casa 10; b7 (G) está na 5ª corda casa 10 e na 2ª corda casa 8. A randomização é a ferramenta que transforma memorização em fluência: sob comando, você encontra qualquer intervalo em qualquer shape. A regra continua: 4 → b3 e b7 → 1.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma D (Dm) — Am na região 7–10",
    "whatToSee": [
        "O mapa completo do Shape 2: 1, b3, 4, 5 e b7.",
        "As quartas D: 6ª corda casa 10, 3ª corda casa 7 e 1ª corda casa 10.",
        "As sétimas menores G: 5ª corda casa 10 e 2ª corda casa 8.",
        "As resoluções 4 → b3 e b7 → 1 dentro do Shape 2.",
    ],
    "chordScaleRelation": "As tensões 4 (D) e b7 (G) do Shape 2 cercam os chord tones (1, b3, 5) e sempre resolvem neles: 4 desce para b3, b7 sobe para 1.",
    "fretboard": {
        "shape": 2, "position": 7, "highlight": ["1", "b3", "4", "5", "b7"],
        "intervalMap": "e|--b3(8)----4(10)--\nB|--b7(8)----1(10)--\nG|--4(7)-----5(9)---\nD|--1(7)-----b3(10)-\nA|--5(7)-----b7(10)-\nE|--b3(8)----4(10)--",
        "tab": "e|------------------8-10-|\nB|--------------8-10-----|\nG|----------7-9----------|\nD|------7-10-------------|\nA|--7-10-----------------|\nE|--8-10-----------------|",
    },
    "exercises": [
        "Localizar todas as 4 (D) no Shape 2.",
        "Localizar todas as b7 (G) no Shape 2.",
        "Randomização: sob comando, encontrar b7, depois 5, depois b3, depois 4, depois 1 no Shape 2.",
        "Randomização misturada: encontrar o mesmo intervalo alternando entre Shape 1 e Shape 2.",
        "Resolução 4 → b3 no Shape 2.",
        "Resolução b7 → 1 no Shape 2.",
    ],
    "earTraining": {"instruction": "Toque D (3ª corda casa 7) e cante Quatro, depois C (4ª corda casa 10) e cante Terça menor. Depois G (5ª corda casa 10) cantando Sétima, resolvendo em A (4ª corda casa 7) cantando Um."},
    "improvisation": {"instruction": "Improvisar sobre A menor alternando Shape 1 e Shape 2 a cada 2 frases. Obrigação: incluir pelo menos uma resolução 4 → b3 e uma b7 → 1 em cada shape."},
    "theoryRoutine": [
        "00–08 min: Localizar 4 e b7 no Shape 2.",
        "08–16 min: Randomização de intervalos no Shape 2.",
        "16–24 min: Randomização misturando Shape 1 e Shape 2.",
        "24–30 min: Improvisação com resoluções obrigatórias.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Fluência entre shapes e palhetada contínua",
        "routine": [
            "00–08 min: Shape 2 completo a 65 BPM.",
            "08–18 min: Células 4 → b3 e b7 → 1 no Shape 2.",
            "18–26 min: Conectar Shape 1 e Shape 2 sem pausa.",
            "26–30 min: Improviso técnico a 80 BPM mantendo o tempo.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Song References For Interval Ear Training", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/song-references-for-interval-ear-training-et-099", "reason": "Ajuda a ouvir 4 e b7 através de referências de músicas conhecidas."},
    "commonMistakes": [
        "Randomizar apenas dentro de um shape e esquecer de misturar os dois.",
        "Confundir a posição de 4 e b7 entre Shape 1 e Shape 2.",
        "Resolver tensões no lugar errado (4 → 5 em vez de 4 → b3).",
    ],
    "mastery": {
        "know": "Sei localizar 4 e b7 no Shape 2 e suas resoluções naturais.",
        "play": "Consigo randomizar intervalos alternando Shape 1 e Shape 2.",
        "use": "Consigo improvisar misturando os shapes com tensão e resolução.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2: 1, b3 e 5 (Aula 4)."],
    "challenge": "Peça a alguém (ou use um app) para ditar shape + intervalo em ordem aleatória e encontre cada um em menos de 3 segundos.",
    "mission": "Gravar uma improvisação de 2 minutos alternando Shape 1 e Shape 2.",
    "xp": XP,
})

L.append({
    "id": 6, "week": 2, "day": 1, "phase": 1,
    "title": "Shape 2 musical: conectando Shape 1 → Shape 2",
    "subtitle": "Frases com intenção e a primeira conexão horizontal",
    "objective": "Usar o Shape 2 musicalmente e conectar o Shape 1 ao Shape 2 com slides, terminando frases em chord tones e usando 4 e b7 como tensão.",
    "prerequisite": "Aulas 4 e 5: Shape 2 completo.",
    "concept": "Agora o Shape 2 vira música. Improvise sobre Am terminando frases em 1, b3 ou 5, usando 4 e b7 como tensão. Depois conecte os dois shapes: um slide de uma nota comum (como A na 4ª corda casa 7, ou D na 3ª corda casa 7) transporta você de uma região para a outra sem perder a orientação. O slide é uma decisão musical — você o usa quando quer unir duas regiões, não por acaso.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma D (Dm) — Am na região 7–10",
    "whatToSee": [
        "Os chord tones 1, b3 e 5 como destinos das frases no Shape 2.",
        "As tensões 4 e b7 como impulso de movimento.",
        "A nota de ligação entre Shape 1 e Shape 2 (ex.: A na 4ª corda casa 7).",
        "O slide como transporte horizontal entre as regiões.",
    ],
    "chordScaleRelation": "Ao conectar os shapes, o acorde Am é a constante: onde quer que você esteja, 1, b3 e 5 são os pontos seguros e 4/b7 as tensões que voltam para eles.",
    "fretboard": {
        "shape": 2, "position": 7, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--b3(8)----4(10)--\nB|--b7(8)----1(10)--\nG|--4(7)-----5(9)---\nD|--1(7)-----b3(10)-\nA|--5(7)-----b7(10)-\nE|--b3(8)----4(10)--",
        "tab": "e|----------------------|\nB|----------------------|\nG|----------------------|\nD|------7---------------|\nA|--10------------------|\nE|----------10--8-------|",
    },
    "exercises": [
        "Frase terminando em 1 (A): use b7 (G) → 1 (A) no Shape 2.",
        "Frase terminando em b3 (C): use 4 (D) → b3 (C) no Shape 2.",
        "Frase terminando em 5 (E): aproxime por 4 (D) e caia em 5 (E).",
        "Frase usando 4 e b7 como tensão antes de resolver.",
        "Conectar Shape 1 → Shape 2 com um slide a partir de uma nota comum (ex.: A na 4ª corda casa 7).",
        "Conectar Shape 2 → Shape 1 no caminho de volta.",
    ],
    "earTraining": {"instruction": "Toque uma frase no Shape 1 e depois a mesma frase no Shape 2. Feche os olhos e diga qual shape está sendo tocado apenas pelo registro e pela sensação da tônica."},
    "improvisation": {"instruction": "Improvisar sobre A menor: 2 minutos só no Shape 2 com terminações em 1, b3 e 5. Depois 3 minutos conectando Shape 1 → Shape 2 com slides, sempre sabendo em qual chord tone a frase vai pousar."},
    "theoryRoutine": [
        "00–08 min: Frases com terminação em 1, b3 e 5 no Shape 2.",
        "08–16 min: Tensão em 4 e b7 com resolução no Shape 2.",
        "16–24 min: Conexão Shape 1 → Shape 2 com slides.",
        "24–30 min: Improvisação livre conectando os dois shapes.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Slides e controle de transição entre shapes",
        "routine": [
            "00–08 min: Slides de 1 tom entre notas comuns dos dois shapes.",
            "08–18 min: Ligar Shape 1 e Shape 2 subindo e descendo o braço.",
            "18–26 min: Frases com slide no início e resolução em chord tone.",
            "26–30 min: Improviso técnico a 80 BPM alternando as regiões.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Introduction To 5 Pattern Play", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/introduction-to-5-pattern-play-bl-601", "reason": "Mostra como tocar entre os padrões da pentatônica, essencial para a conexão Shape 1 → Shape 2."},
    "commonMistakes": [
        "Fazer slide sem saber qual nota está ligando os dois shapes.",
        "Perder a orientação da tônica ao mudar de região.",
        "Tratar a conexão como corrida em vez de movimento musical.",
    ],
    "mastery": {
        "know": "Entendo que o slide conecta regiões através de notas comuns do acorde Am.",
        "play": "Consigo conectar Shape 1 e Shape 2 com slides sem perder a tônica.",
        "use": "Consigo improvisar atravessando os dois shapes com intenção e resolução.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2 completo (Aula 5)."],
    "challenge": "Grave uma frase começando no Shape 1, deslizando para o Shape 2 e terminando em chord tone.",
    "mission": "Gravar 2 minutos conectando Shape 1 → Shape 2 e de volta, com pelo menos 3 slides.",
    "xp": XP,
})

L.append({
    "id": 7, "week": 2, "day": 2, "phase": 1,
    "title": "Shape 3 + CAGED: o acorde na região 9–13",
    "subtitle": "Shape 3 ancorado no acorde Am (forma C)",
    "objective": "Introduzir o Shape 3 (região 9–13), reconhecendo o acorde Am (forma C) e localizando 1, b3 e 5, revisando os Shapes 1 e 2.",
    "prerequisite": "Shapes 1 e 2 com 1, b3 e 5 dominados.",
    "concept": "O Shape 3 vive nas casas 9 a 13. Aqui a tônica A está na 5ª corda casa 12 e na 2ª corda casa 10; a terça menor C na 4ª corda casa 10 e na 2ª corda casa 13; a quinta E na 3ª corda casa 9 e na 1ª corda casa 12. O acorde Am (forma C) ancorado na 5ª corda casa 12 usa essas mesmas notas. A abertura maior (corda B com casas 10 e 13) exige esticar o dedo 4. Revise os Shapes 1 e 2 antes de mergulhar no 3.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma C (Cm) — Am na região 9–13",
    "whatToSee": [
        "O acorde Am (forma C): 5ª corda casa 12 (A), 4ª corda casa 10 (C), 3ª corda casa 9 (E), 2ª corda casa 10 (A) e 1ª corda casa 12 (E).",
        "As tônicas A: 5ª corda casa 12 e 2ª corda casa 10.",
        "As terças menores C: 4ª corda casa 10 e 2ª corda casa 13.",
        "As quintas E: 3ª corda casa 9 e 1ª corda casa 12.",
    ],
    "chordScaleRelation": "O Shape 3 é o acorde Am (forma C) aberto ao redor. Os chord tones (1, b3, 5) são os mesmos de sempre; o que muda é apenas a geografia no braço.",
    "fretboard": {
        "shape": 3, "position": 9, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--4(10)----5(12)--\nB|--1(10)----b3(13)-\nG|--5(9)-----b7(12)-\nD|--b3(10)---4(12)--\nA|--b7(10)---1(12)--\nE|--4(10)----5(12)--",
        "tab": "e|-----------12-|\nB|---------10---|\nG|-------9------|\nD|-----10-------|\nA|--12----------|\nE|--------------|",
    },
    "exercises": [
        "Tocar o acorde Am (forma C) e nomear as notas: A, C, E, A, E.",
        "Localizar todas as tônicas 1 (A) no Shape 3.",
        "Localizar todas as terças menores b3 (C) no Shape 3.",
        "Localizar todas as quintas 5 (E) no Shape 3.",
        "Revisar os Shapes 1 e 2: localizar 1, b3 e 5 em cada um.",
        "Improvisação curta usando só chord tones no Shape 3.",
    ],
    "earTraining": {"instruction": "Toque A (5ª corda casa 12) e cante Um. Toque C (4ª corda casa 10) e cante Terça menor. Toque E (3ª corda casa 9) e cante Quinta. Compare com os Shapes 1 e 2 e perceba a mesma identidade sonora."},
    "improvisation": {"instruction": "Com backing track em A menor, improvise usando só 1, b3 e 5 no Shape 3. Toda frase termina em chord tone. Depois revisite rapidamente os Shapes 1 e 2 para manter o mapa completo."},
    "theoryRoutine": [
        "00–10 min: Acorde Am (forma C) e chord tones no Shape 3.",
        "10–18 min: Revisão dos Shapes 1 e 2.",
        "18–27 min: Improvisação com chord tones no Shape 3.",
        "27–30 min: Teste aleatório nos três shapes.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Abertura do dedo 4 e sincronização no Shape 3",
        "routine": [
            "00–08 min: Shape 3 em colcheias a 55 BPM.",
            "08–18 min: Alongamento do dedo 4 na corda B (casas 10–13).",
            "18–26 min: Arpejo do acorde Am (forma C).",
            "26–30 min: Rodar os três shapes a 70 BPM.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Minor Pentatonic Pattern 3", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/minor-pentatonic-pattern-3-bl-602", "reason": "Introduz a região do Shape 3 na 9ª–13ª casa."},
    "commonMistakes": [
        "Não esticar o dedo 4 na corda B, perdendo a terça menor C.",
        "Esquecer de revisar os Shapes 1 e 2 ao estudar o 3.",
        "Perder a tônica A da 5ª corda casa 12.",
    ],
    "mastery": {
        "know": "Sei que o Shape 3 é o Am (forma C) na região 9–13.",
        "play": "Consigo localizar 1, b3 e 5 no Shape 3 com a abertura correta.",
        "use": "Consigo improvisar em chord tones no Shape 3 e revisitar os anteriores.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2 completo (Aula 5)."],
    "challenge": "Toque a mesma frase de chord tones nos Shapes 1, 2 e 3, sem parar.",
    "mission": "Gravar os três shapes com 1, b3 e 5, nomeando os intervalos.",
    "xp": XP,
})

L.append({
    "id": 8, "week": 2, "day": 3, "phase": 1,
    "title": "Shape 3 completo: 4 e b7 + randomização",
    "subtitle": "Mapa completo do Shape 3 e randomização shape + intervalo",
    "objective": "Completar o Shape 3 com 4 e b7, e praticar randomização combinando Shape 3 com cada intervalo, revisando Shapes 1 e 2.",
    "prerequisite": "Aula 7: 1, b3 e 5 no Shape 3.",
    "concept": "No Shape 3, a quarta 4 (D) está na 6ª corda casa 10, na 4ª corda casa 12 e na 1ª corda casa 10; a sétima menor b7 (G) está na 5ª corda casa 10 e na 3ª corda casa 12. A randomização shape + intervalo (ex.: Shape 3 + b3, Shape 3 + b7) é o que consolida o mapa: você deve encontrar o intervalo sem pensar no desenho. As resoluções seguem as mesmas: 4 → b3 e b7 → 1.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma C (Cm) — Am na região 9–13",
    "whatToSee": [
        "O mapa completo do Shape 3: 1, b3, 4, 5 e b7.",
        "As quartas D: 6ª corda casa 10, 4ª corda casa 12 e 1ª corda casa 10.",
        "As sétimas menores G: 5ª corda casa 10 e 3ª corda casa 12.",
        "As resoluções 4 → b3 e b7 → 1 no Shape 3.",
    ],
    "chordScaleRelation": "As tensões 4 (D) e b7 (G) do Shape 3 cercam os chord tones e resolvem neles exatamente como nos shapes anteriores.",
    "fretboard": {
        "shape": 3, "position": 9, "highlight": ["1", "b3", "4", "5", "b7"],
        "intervalMap": "e|--4(10)----5(12)--\nB|--1(10)----b3(13)-\nG|--5(9)-----b7(12)-\nD|--b3(10)---4(12)--\nA|--b7(10)---1(12)--\nE|--4(10)----5(12)--",
        "tab": "e|------------------10-12-|\nB|--------------10-13-----|\nG|----------9-12----------|\nD|------10-12-------------|\nA|--10-12-----------------|\nE|--10-12-----------------|",
    },
    "exercises": [
        "Localizar todas as 4 (D) no Shape 3.",
        "Localizar todas as b7 (G) no Shape 3.",
        "Randomização: Shape 3 + 1, Shape 3 + b3, Shape 3 + 4, Shape 3 + 5, Shape 3 + b7.",
        "Resolução 4 → b3 no Shape 3.",
        "Resolução b7 → 1 no Shape 3.",
        "Revisar Shapes 1 e 2 completos.",
    ],
    "earTraining": {"instruction": "Toque D (4ª corda casa 12) e cante Quatro, resolvendo em C (4ª corda casa 10) cantando Terça menor. Depois G (3ª corda casa 12) cantando Sétima, resolvendo em A (5ª corda casa 12) cantando Um."},
    "improvisation": {"instruction": "Improvisar sobre A menor no Shape 3, usando 4 e b7 como tensão e resolvendo em chord tones. A cada 2 frases, revisite os Shapes 1 e 2 para manter o mapa completo."},
    "theoryRoutine": [
        "00–08 min: Localizar 4 e b7 no Shape 3.",
        "08–18 min: Randomização shape + intervalo no Shape 3.",
        "18–24 min: Resoluções 4 → b3 e b7 → 1.",
        "24–30 min: Improvisação com revisão dos shapes anteriores.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Precisão de mudança de posição e palhetada",
        "routine": [
            "00–08 min: Shape 3 completo a 60 BPM.",
            "08–18 min: Células 4 → b3 e b7 → 1 no Shape 3.",
            "18–26 min: Conectar Shapes 1, 2 e 3 em sequência.",
            "26–30 min: Rodar os três shapes a 75 BPM.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Notes & Chord Relationships", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/notes-chord-relationships-sc-160", "reason": "Conecta as notas da escala às notas do acorde (chord tones), núcleo desta aula."},
    "commonMistakes": [
        "Randomizar apenas dentro do Shape 3 sem revisar os anteriores.",
        "Confundir a posição de 4 e b7 entre os três shapes.",
        "Resolver 4 → 5 em vez de 4 → b3.",
    ],
    "mastery": {
        "know": "Sei localizar 4 e b7 no Shape 3 e suas resoluções.",
        "play": "Consigo randomizar shape + intervalo nos Shapes 1, 2 e 3.",
        "use": "Consigo improvisar no Shape 3 com tensão e resolução consciente.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2 completo (Aula 5).", "Shape 3: 1, b3 e 5 (Aula 7)."],
    "challenge": "Ditado aleatório: peça shape + intervalo e encontre em menos de 3 segundos nos Shapes 1, 2 e 3.",
    "mission": "Gravar a randomização shape + intervalo nos três shapes.",
    "xp": XP,
})

L.append({
    "id": 9, "week": 2, "day": 4, "phase": 1,
    "title": "Shape 3 musical: conectando Shape 2 → Shape 3",
    "subtitle": "Frases com obrigações de resolução e conexão 2 → 3",
    "objective": "Usar o Shape 3 musicalmente e conectar o Shape 2 ao Shape 3, cumprindo obrigações de terminação em 1, b3 e 5 e de resoluções 4 → b3 e b7 → 1.",
    "prerequisite": "Aula 8: Shape 3 completo.",
    "concept": "O Shape 3 é a ponte entre o meio e o agudo do braço. Ao conectar Shape 2 → Shape 3, use notas comuns (A na 2ª corda casa 10, ou D na 1ª corda casa 10) como dobradiça. Suas frases agora têm obrigações claras: uma termina em 1, outra em b3, outra em 5, uma usa 4 → b3 e uma usa b7 → 1. Essas regras não limitam — elas garantem que você esteja sempre escolhendo conscientemente onde pousar.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma C (Cm) — Am na região 9–13",
    "whatToSee": [
        "Os chord tones 1, b3 e 5 como destinos no Shape 3.",
        "As tensões 4 e b7 como impulso no Shape 3.",
        "A dobradiça entre Shape 2 e Shape 3 (ex.: A na 2ª corda casa 10).",
        "O slide de conexão subindo em direção ao agudo.",
    ],
    "chordScaleRelation": "Conectar Shape 2 → Shape 3 é mover-se no mesmo acorde Am. As dobradiças são sempre chord tones (A, C ou E) ou tensões (D, G) que você escolhe resolver.",
    "fretboard": {
        "shape": 3, "position": 9, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--4(10)----5(12)--\nB|--1(10)----b3(13)-\nG|--5(9)-----b7(12)-\nD|--b3(10)---4(12)--\nA|--b7(10)---1(12)--\nE|--4(10)----5(12)--",
        "tab": "e|----------------------|\nB|----------------------|\nG|----------------------|\nD|------12--10----------|\nA|--10--12--------------|\nE|----------------------|",
    },
    "exercises": [
        "Uma frase termina em 1 (A) no Shape 3.",
        "Uma frase termina em b3 (C) no Shape 3.",
        "Uma frase termina em 5 (E) no Shape 3.",
        "Uma frase usa 4 → b3 no Shape 3.",
        "Uma frase usa b7 → 1 no Shape 3.",
        "Conectar Shape 2 → Shape 3 com slide a partir de A (2ª corda casa 10).",
    ],
    "earTraining": {"instruction": "Toque uma frase no Shape 2 e a mesma frase no Shape 3. Cante a nota de chegada antes de tocar. Perceba que a tônica A agora aparece na 5ª corda casa 12."},
    "improvisation": {"instruction": "Improvisar sobre A menor cumprindo as 5 obrigações: frase em 1, em b3, em 5, com 4 → b3 e com b7 → 1. Depois conectar Shape 2 → Shape 3 com slides e repetir o ciclo."},
    "theoryRoutine": [
        "00–08 min: Frases com terminação em 1, b3 e 5 no Shape 3.",
        "08–16 min: Obrigações de resolução 4 → b3 e b7 → 1.",
        "16–24 min: Conexão Shape 2 → Shape 3 com slides.",
        "24–30 min: Improvisação completa cumprindo todas as obrigações.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Slides ascendentes e controle rítmico",
        "routine": [
            "00–08 min: Slides de 1 tom subindo entre Shapes 2 e 3.",
            "08–18 min: Frases com slide no início e pouso em chord tone.",
            "18–26 min: Ligar Shape 1 → 2 → 3 em sequência.",
            "26–30 min: Improviso técnico a 80 BPM.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "The Mental Fretboard Development", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/the-mental-fretboard-development-et-303", "reason": "Desenvolve a visualização mental do braço, fundamental para conectar Shape 2 → Shape 3."},
    "commonMistakes": [
        "Ignorar as obrigações de resolução e improvisar no piloto automático.",
        "Perder a dobradiça entre os shapes ao subir o braço.",
        "Confundir a tônica A da 5ª corda casa 12 com a da 2ª corda casa 10.",
    ],
    "mastery": {
        "know": "Entendo as 5 obrigações de frase e a dobradiça Shape 2 → Shape 3.",
        "play": "Consigo cumprir as terminações em 1, b3 e 5 e as resoluções 4 → b3 e b7 → 1.",
        "use": "Consigo conectar Shape 2 → Shape 3 improvisando com intenção.",
    },
    "review": ["Shape 2 musical (Aula 6).", "Shape 3 completo (Aula 8)."],
    "challenge": "Grave 5 frases seguidas, cada uma cumprindo uma das 5 obrigações, conectando Shape 2 → Shape 3.",
    "mission": "Gravar 2 minutos improvisando com as 5 obrigações cumpridas.",
    "xp": XP,
})

L.append({
    "id": 10, "week": 2, "day": 5, "phase": 1,
    "title": "Shape 4 + CAGED: o acorde na região 12–15",
    "subtitle": "Shape 4 ancorado no acorde Am (forma A)",
    "objective": "Introduzir o Shape 4 (região 12–15), reconhecendo o acorde Am (forma A) e localizando 1, b3 e 5, revisando os Shapes 1 a 3.",
    "prerequisite": "Shapes 1 a 3 com 1, b3 e 5 dominados.",
    "concept": "O Shape 4 vive nas casas 12 a 15. A tônica A está na 5ª corda casa 12 e na 3ª corda casa 14; a terça menor C na 5ª corda casa 15 e na 2ª corda casa 13; a quinta E na 6ª corda casa 12, na 4ª corda casa 14 e na 1ª corda casa 12. O acorde Am (forma A) usa A, C e E exatamente nessa região. Como estamos subindo o braço, o espaço entre os trastes diminui e a digitação fica mais confortável. Revisite os Shapes 1 a 3 para manter o mapa completo.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma A (Am) — Am na região 12–15",
    "whatToSee": [
        "O acorde Am (forma A): 5ª corda casa 12 (A), 4ª corda casa 14 (E), 3ª corda casa 14 (A), 2ª corda casa 13 (C) e 1ª corda casa 12 (E).",
        "As tônicas A: 5ª corda casa 12 e 3ª corda casa 14.",
        "As terças menores C: 5ª corda casa 15 e 2ª corda casa 13.",
        "As quintas E: 6ª corda casa 12, 4ª corda casa 14 e 1ª corda casa 12.",
    ],
    "chordScaleRelation": "O Shape 4 é o acorde Am (forma A) aberto ao redor. Mesmos chord tones (1, b3, 5), apenas mais agudos e próximos uns dos outros.",
    "fretboard": {
        "shape": 4, "position": 12, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--5(12)----b7(15)-\nB|--b3(13)---4(15)--\nG|--b7(12)---1(14)--\nD|--4(12)----5(14)--\nA|--1(12)----b3(15)-\nE|--5(12)----b7(15)-",
        "tab": "e|-----------12-|\nB|---------13---|\nG|-------14-----|\nD|-----14-------|\nA|--12----------|\nE|--------------|",
    },
    "exercises": [
        "Tocar o acorde Am (forma A) e nomear as notas: A, E, A, C, E.",
        "Localizar todas as tônicas 1 (A) no Shape 4.",
        "Localizar todas as terças menores b3 (C) no Shape 4.",
        "Localizar todas as quintas 5 (E) no Shape 4.",
        "Revisar os Shapes 1 a 3: localizar 1, b3 e 5 em cada um.",
        "Improvisação curta usando só chord tones no Shape 4.",
    ],
    "earTraining": {"instruction": "Toque A (5ª corda casa 12) e cante Um. Toque C (2ª corda casa 13) e cante Terça menor. Toque E (4ª corda casa 14) e cante Quinta. O registro é mais agudo, mas a sensação harmônica é a mesma."},
    "improvisation": {"instruction": "Com backing track em A menor, improvise usando só 1, b3 e 5 no Shape 4, terminando frases em chord tone. Depois revisite os Shapes 1 a 3 para manter o mapa completo."},
    "theoryRoutine": [
        "00–10 min: Acorde Am (forma A) e chord tones no Shape 4.",
        "10–18 min: Revisão dos Shapes 1 a 3.",
        "18–27 min: Improvisação com chord tones no Shape 4.",
        "27–30 min: Teste aleatório nos quatro shapes.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Conforto no registro agudo e sincronização",
        "routine": [
            "00–08 min: Shape 4 em colcheias a 60 BPM.",
            "08–18 min: Arpejo do acorde Am (forma A).",
            "18–26 min: Conectar Shapes 1 a 4 em sequência.",
            "26–30 min: Rodar os quatro shapes a 75 BPM.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Minor Pentatonic Pattern 4", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/minor-pentatonic-pattern-4-bl-605", "reason": "Introduz a região do Shape 4 na 12ª–15ª casa."},
    "commonMistakes": [
        "Confundir a tônica A da 5ª corda casa 12 com a da 3ª corda casa 14.",
        "Deixar de revisar os shapes anteriores ao subir o braço.",
        "Tocar as notas do agudo sem afinação limpa.",
    ],
    "mastery": {
        "know": "Sei que o Shape 4 é o Am (forma A) na região 12–15.",
        "play": "Consigo localizar 1, b3 e 5 no Shape 4 com conforto.",
        "use": "Consigo improvisar em chord tones no Shape 4 revisando os anteriores.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2 completo (Aula 5).", "Shape 3 completo (Aula 8)."],
    "challenge": "Toque a mesma frase de chord tones nos Shapes 1, 2, 3 e 4 sem parar.",
    "mission": "Gravar os quatro shapes com 1, b3 e 5, nomeando os intervalos.",
    "xp": XP,
})

L.append({
    "id": 11, "week": 3, "day": 1, "phase": 1,
    "title": "Shape 4 completo: 4 e b7 + randomização",
    "subtitle": "Mapa completo do Shape 4, ouvido e randomização",
    "objective": "Completar o Shape 4 com 4 e b7, com exercícios auditivos, de localização e de randomização, revisando os shapes anteriores.",
    "prerequisite": "Aula 10: 1, b3 e 5 no Shape 4.",
    "concept": "No Shape 4, a quarta 4 (D) está na 4ª corda casa 12 e na 2ª corda casa 15; a sétima menor b7 (G) está na 6ª corda casa 15, na 3ª corda casa 12 e na 1ª corda casa 15. Continue randomizando shape + intervalo (agora com quatro shapes) e associe cada intervalo ao seu som. A revisão dos shapes anteriores é metade do trabalho: o Shape 1 não pode desaparecer quando você chega ao Shape 4.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma A (Am) — Am na região 12–15",
    "whatToSee": [
        "O mapa completo do Shape 4: 1, b3, 4, 5 e b7.",
        "As quartas D: 4ª corda casa 12 e 2ª corda casa 15.",
        "As sétimas menores G: 6ª corda casa 15, 3ª corda casa 12 e 1ª corda casa 15.",
        "As resoluções 4 → b3 e b7 → 1 no Shape 4.",
    ],
    "chordScaleRelation": "As tensões 4 (D) e b7 (G) do Shape 4 resolvem nos chord tones como em todo o curso: 4 desce para b3 e b7 sobe para 1.",
    "fretboard": {
        "shape": 4, "position": 12, "highlight": ["1", "b3", "4", "5", "b7"],
        "intervalMap": "e|--5(12)----b7(15)-\nB|--b3(13)---4(15)--\nG|--b7(12)---1(14)--\nD|--4(12)----5(14)--\nA|--1(12)----b3(15)-\nE|--5(12)----b7(15)-",
        "tab": "e|------------------12-15-|\nB|--------------13-15-----|\nG|----------12-14---------|\nD|------12-14-------------|\nA|--12-15-----------------|\nE|--12-15-----------------|",
    },
    "exercises": [
        "Localizar todas as 4 (D) no Shape 4.",
        "Localizar todas as b7 (G) no Shape 4.",
        "Randomização: Shape 4 + 1, Shape 4 + b3, Shape 4 + 4, Shape 4 + 5, Shape 4 + b7.",
        "Exercício auditivo: tocar 1, depois b3, depois 5 e reconhecer cada som.",
        "Resolução 4 → b3 no Shape 4.",
        "Resolução b7 → 1 no Shape 4.",
        "Revisar Shapes 1 a 3 completos.",
    ],
    "earTraining": {"instruction": "Toque as cinco notas do Shape 4 em ordem e cante cada intervalo. Depois, com os olhos fechados, toque uma nota aleatória e adivinhe qual intervalo é antes de olhar."},
    "improvisation": {"instruction": "Improvisar sobre A menor no Shape 4, usando 4 e b7 como tensão e resolvendo em chord tones. Alterne com os Shapes 1 a 3 para manter o mapa completo do braço."},
    "theoryRoutine": [
        "00–08 min: Localizar 4 e b7 no Shape 4.",
        "08–18 min: Randomização shape + intervalo nos quatro shapes.",
        "18–24 min: Exercícios auditivos de intervalo.",
        "24–30 min: Improvisação com revisão dos shapes anteriores.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Precisão e fluência nos quatro shapes",
        "routine": [
            "00–08 min: Shape 4 completo a 60 BPM.",
            "08–18 min: Células 4 → b3 e b7 → 1 no Shape 4.",
            "18–26 min: Conectar Shapes 1 a 4 em sequência.",
            "26–30 min: Rodar os quatro shapes a 80 BPM.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Minor Pentatonic: The 5 Patterns", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/minor-pentatonic-the-5-patterns-sc-304", "reason": "Revisa os 5 padrões de uma vez, útil para consolidar o Shape 4 dentro do mapa completo."},
    "commonMistakes": [
        "Deixar o Shape 1 desaparecer ao estudar o Shape 4.",
        "Randomizar só no Shape 4 sem revisar os anteriores.",
        "Confundir 4 e b7 entre os shapes ao subir o braço.",
    ],
    "mastery": {
        "know": "Sei localizar 4 e b7 no Shape 4 e suas resoluções.",
        "play": "Consigo randomizar shape + intervalo nos Shapes 1 a 4.",
        "use": "Consigo improvisar no Shape 4 com tensão e resolução consciente.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2 completo (Aula 5).", "Shape 3 completo (Aula 8).", "Shape 4: 1, b3 e 5 (Aula 10)."],
    "challenge": "Ditado aleatório nos quatro shapes: encontre qualquer intervalo em menos de 3 segundos.",
    "mission": "Gravar a randomização shape + intervalo nos quatro shapes.",
    "xp": XP,
})

L.append({
    "id": 12, "week": 3, "day": 2, "phase": 1,
    "title": "Shape 4 musical: conectando Shape 3 → Shape 4",
    "subtitle": "Técnica a serviço da música: slides, bends, vibrato e silêncio",
    "objective": "Conectar o Shape 3 ao Shape 4 aplicando slides, bends, vibrato e silêncio, sempre sabendo qual intervalo está sendo usado antes de executar a técnica.",
    "prerequisite": "Aula 11: Shape 4 completo.",
    "concept": "A técnica só tem valor quando está a serviço da música. Antes de fazer um slide, um bend ou um vibrato, pergunte: qual intervalo estou tocando e para onde ele quer ir? Um bend de 4 (D) deve mirar em b3 (C) ou 5 (E); um vibrato pertence à nota de chegada; o silêncio prepara a próxima frase. Conectar Shape 3 → Shape 4 é subir o braço mantendo o acorde Am como referência constante.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma A (Am) — Am na região 12–15",
    "whatToSee": [
        "Os chord tones 1, b3 e 5 como destinos no Shape 4.",
        "As tensões 4 e b7 como impulso no Shape 4.",
        "A dobradiça entre Shape 3 e Shape 4 (ex.: A na 5ª corda casa 12).",
        "O slide subindo para o agudo e o bend com nota-alvo.",
    ],
    "chordScaleRelation": "Ao conectar Shape 3 → Shape 4, o acorde Am não muda: as técnicas apenas realçam a viagem entre as tensões (4, b7) e os chord tones (1, b3, 5).",
    "fretboard": {
        "shape": 4, "position": 12, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--5(12)----b7(15)-\nB|--b3(13)---4(15)--\nG|--b7(12)---1(14)--\nD|--4(12)----5(14)--\nA|--1(12)----b3(15)-\nE|--5(12)----b7(15)-",
        "tab": "e|----------------------|\nB|------15--13----------|\nG|--12--14--------------|\nD|----------------------|\nA|----------------------|\nE|----------------------|",
    },
    "exercises": [
        "Slide: de G (b7) na 3ª corda casa 12 para A (1) na 3ª corda casa 14.",
        "Bend: dobre D (4) na 2ª corda casa 15 subindo em direção a E (5).",
        "Vibrato: aplique vibrato apenas na nota de chegada (1, b3 ou 5).",
        "Silêncio: toque uma frase, respire 2 tempos e toque a resposta.",
        "Antes de cada técnica, diga em voz alta qual intervalo está prestes a executar.",
        "Conectar Shape 3 → Shape 4 com slide a partir de A (5ª corda casa 12).",
    ],
    "earTraining": {"instruction": "Toque 4 (D) e cante Quatro, depois dobre para 5 (E) cantando Quinta. Toque b7 (G) e cante Sétima, depois suba para 1 (A) cantando Um. Sinta o bend como um caminho auditivo, não um gesto mecânico."},
    "improvisation": {"instruction": "Improvisar sobre A menor conectando Shape 3 → Shape 4, usando slides, bends, vibrato e silêncio. Regra: antes de cada técnica, você deve saber qual intervalo está usando e para onde ele resolve."},
    "theoryRoutine": [
        "00–08 min: Revisão dos intervalos no Shape 4.",
        "08–16 min: Slide, bend e vibrato com nota-alvo consciente.",
        "16–24 min: Conexão Shape 3 → Shape 4.",
        "24–30 min: Improvisação musical com todas as técnicas.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Bends, vibrato e silêncio no registro agudo",
        "routine": [
            "00–08 min: Bend de tom inteiro (b7 → 1) e de meio tom (4 → 5).",
            "08–18 min: Vibrato controlado na nota de chegada.",
            "18–26 min: Slides ascendentes entre Shapes 3 e 4.",
            "26–30 min: Frase completa com bend → vibrato → silêncio.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Blues Vibrato", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/blues-vibrato-bl-405", "reason": "Aprofunda o vibrato como ferramenta expressiva na nota de chegada."},
    "commonMistakes": [
        "Fazer bend sem saber a nota-alvo.",
        "Vibrar nota de passagem em vez da nota de chegada.",
        "Usar slide sem entender qual nota está ligando os shapes.",
    ],
    "mastery": {
        "know": "Entendo como slide, bend, vibrato e silêncio servem à música.",
        "play": "Consigo executar cada técnica sabendo o intervalo e a nota-alvo.",
        "use": "Consigo conectar Shape 3 → Shape 4 improvisando com intenção.",
    },
    "review": ["Shape 3 musical (Aula 9).", "Shape 4 completo (Aula 11)."],
    "challenge": "Grave uma frase com slide, uma com bend, uma com vibrato e uma com silêncio, sempre nomeando o intervalo usado.",
    "mission": "Gravar 2 minutos conectando Shape 3 → Shape 4 com as quatro técnicas.",
    "xp": XP,
})

L.append({
    "id": 13, "week": 3, "day": 3, "phase": 1,
    "title": "Shape 5 + CAGED: o acorde na região 14–17",
    "subtitle": "Shape 5 ancorado no acorde Am (forma G)",
    "objective": "Introduzir o Shape 5 (região 14–17), reconhecendo o acorde Am (forma G) e localizando 1, b3 e 5, revisando os Shapes 1 a 4.",
    "prerequisite": "Shapes 1 a 4 com 1, b3 e 5 dominados.",
    "concept": "O Shape 5 fecha o ciclo na região 14 a 17. A tônica A está na 6ª corda casa 17 e na 3ª corda casa 14; a terça menor C na 5ª corda casa 15 e na 3ª corda casa 17; a quinta E na 4ª corda casa 14, na 2ª corda casa 17 e na 1ª corda casa 17. O acorde Am (forma G) usa essas notas. Ao dominar os cinco shapes, o braço inteiro vira um mapa contínuo de Am. Revise os Shapes 1 a 4 antes de mergulhar no 5.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma G (Gm) — Am na região 14–17",
    "whatToSee": [
        "O acorde Am (forma G): 6ª corda casa 17 (A), 5ª corda casa 15 (C), 4ª corda casa 14 (E), 3ª corda casa 14 (A), 2ª corda casa 17 (E) e 1ª corda casa 17 (A).",
        "As tônicas A: 6ª corda casa 17 e 3ª corda casa 14.",
        "As terças menores C: 5ª corda casa 15 e 3ª corda casa 17.",
        "As quintas E: 4ª corda casa 14, 2ª corda casa 17 e 1ª corda casa 17.",
    ],
    "chordScaleRelation": "O Shape 5 é o acorde Am (forma G) no topo do braço. Mesmos chord tones (1, b3, 5), fechando o ciclo dos cinco shapes.",
    "fretboard": {
        "shape": 5, "position": 14, "highlight": ["1", "b3", "5"],
        "intervalMap": "e|--b7(15)---1(17)--\nB|--4(15)----5(17)--\nG|--1(14)----b3(17)-\nD|--5(14)----b7(17)-\nA|--b3(15)---4(17)--\nE|--b7(15)---1(17)--",
        "tab": "e|--------------17-|\nB|------------17---|\nG|----------14-----|\nD|--------14-------|\nA|------15---------|\nE|--17-------------|",
    },
    "exercises": [
        "Tocar o acorde Am (forma G) e nomear as notas: A, C, E, A, E, A.",
        "Localizar todas as tônicas 1 (A) no Shape 5.",
        "Localizar todas as terças menores b3 (C) no Shape 5.",
        "Localizar todas as quintas 5 (E) no Shape 5.",
        "Revisar os Shapes 1 a 4: localizar 1, b3 e 5 em cada um.",
        "Improvisação curta usando só chord tones no Shape 5.",
    ],
    "earTraining": {"instruction": "Toque A (6ª corda casa 17) e cante Um. Toque C (5ª corda casa 15) e cante Terça menor. Toque E (4ª corda casa 14) e cante Quinta. No registro mais agudo, a identidade do acorde Am permanece intacta."},
    "improvisation": {"instruction": "Com backing track em A menor, improvise usando só 1, b3 e 5 no Shape 5, terminando frases em chord tone. Depois revisite os Shapes 1 a 4 para manter o mapa completo."},
    "theoryRoutine": [
        "00–10 min: Acorde Am (forma G) e chord tones no Shape 5.",
        "10–18 min: Revisão dos Shapes 1 a 4.",
        "18–27 min: Improvisação com chord tones no Shape 5.",
        "27–30 min: Teste aleatório nos cinco shapes.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Conforto no topo do braço e sincronização",
        "routine": [
            "00–08 min: Shape 5 em colcheias a 55 BPM.",
            "08–18 min: Arpejo do acorde Am (forma G).",
            "18–26 min: Conectar Shapes 1 a 5 em sequência.",
            "26–30 min: Rodar os cinco shapes a 70 BPM.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Minor Pentatonic Pattern 5", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/minor-pentatonic-pattern-5-bl-608", "reason": "Introduz a região do Shape 5 na 14ª–17ª casa."},
    "commonMistakes": [
        "Perder a tônica A da 6ª corda casa 17 no topo do braço.",
        "Deixar de revisar os shapes anteriores.",
        "Tocar o registro agudo com excesso de força e sem afinação.",
    ],
    "mastery": {
        "know": "Sei que o Shape 5 é o Am (forma G) na região 14–17.",
        "play": "Consigo localizar 1, b3 e 5 no Shape 5 com conforto.",
        "use": "Consigo improvisar em chord tones no Shape 5 revisando os anteriores.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2 completo (Aula 5).", "Shape 3 completo (Aula 8).", "Shape 4 completo (Aula 11)."],
    "challenge": "Toque a mesma frase de chord tones nos Shapes 1 a 5 sem parar, subindo o braço inteiro.",
    "mission": "Gravar os cinco shapes com 1, b3 e 5, nomeando os intervalos.",
    "xp": XP,
})

L.append({
    "id": 14, "week": 3, "day": 4, "phase": 1,
    "title": "Shape 5 completo: enxergando o braço inteiro",
    "subtitle": "Mapa completo do Shape 5 e revisão dos cinco shapes",
    "objective": "Completar o Shape 5 com 4 e b7 e revisar os cinco shapes, começando a visualizar o braço inteiro como um mapa contínuo de Am.",
    "prerequisite": "Aula 13: 1, b3 e 5 no Shape 5.",
    "concept": "No Shape 5, a quarta 4 (D) está na 5ª corda casa 17 e na 2ª corda casa 15; a sétima menor b7 (G) está na 6ª corda casa 15, na 4ª corda casa 17 e na 1ª corda casa 15. Agora o objetivo muda de escala: em vez de um shape, você visualiza o braço inteiro. Encontre todas as tônicas, todas as b3, todas as 5, todas as 4 e todas as b7 — de ponta a ponta. O Shape 1 não é mais uma caixa separada; é a parte grave do mesmo mapa.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "Forma G (Gm) — Am na região 14–17",
    "whatToSee": [
        "O mapa completo do Shape 5: 1, b3, 4, 5 e b7.",
        "As quartas D: 5ª corda casa 17 e 2ª corda casa 15.",
        "As sétimas menores G: 6ª corda casa 15, 4ª corda casa 17 e 1ª corda casa 15.",
        "O braço inteiro como um mapa contínuo de Am.",
    ],
    "chordScaleRelation": "Com os cinco shapes completos, o acorde Am (1, b3, 5) e as tensões (4, b7) aparecem em todo o braço, formando um único mapa contínuo.",
    "fretboard": {
        "shape": 5, "position": 14, "highlight": ["1", "b3", "4", "5", "b7"],
        "intervalMap": "e|--b7(15)---1(17)--\nB|--4(15)----5(17)--\nG|--1(14)----b3(17)-\nD|--5(14)----b7(17)-\nA|--b3(15)---4(17)--\nE|--b7(15)---1(17)--",
        "tab": "e|------------------15-17-|\nB|--------------15-17-----|\nG|----------14-17---------|\nD|------14-17-------------|\nA|--15-17-----------------|\nE|--15-17-----------------|",
    },
    "exercises": [
        "Localizar todas as 4 (D) no Shape 5.",
        "Localizar todas as b7 (G) no Shape 5.",
        "Encontrar todas as tônicas 1 (A) nos cinco shapes.",
        "Encontrar todas as b3 (C) nos cinco shapes.",
        "Encontrar todas as 5 (E) nos cinco shapes.",
        "Encontrar todas as 4 (D) nos cinco shapes.",
        "Encontrar todas as b7 (G) nos cinco shapes.",
    ],
    "earTraining": {"instruction": "Percorra o braço de grave a agudo tocando apenas as tônicas A e cantando Um. Depois repita para b3, 5, 4 e b7. Seu ouvido deve reconhecer cada intervalo em qualquer região."},
    "improvisation": {"instruction": "Improvisar sobre A menor atravessando os cinco shapes livremente, usando chord tones como destino e 4/b7 como tensão. O objetivo é não ficar preso a nenhum shape."},
    "theoryRoutine": [
        "00–08 min: Localizar 4 e b7 no Shape 5.",
        "08–20 min: Revisão dos cinco shapes por intervalo (1, b3, 5, 4, b7).",
        "20–30 min: Improvisação atravessando o braço inteiro.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Fluência horizontal nos cinco shapes",
        "routine": [
            "00–08 min: Shape 5 completo a 60 BPM.",
            "08–18 min: Subir e descer o braço conectando os cinco shapes.",
            "18–26 min: Células de intervalo por todo o braço.",
            "26–30 min: Improviso técnico atravessando o braço a 80 BPM.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "The Mental Fretboard Development", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/the-mental-fretboard-development-et-303", "reason": "Consolida a visualização mental de todo o braço, objetivo desta aula."},
    "commonMistakes": [
        "Ainda pensar em shapes separados em vez de um mapa contínuo.",
        "Encontrar tônicas só no grave e perder as do agudo.",
        "Não revisar o Shape 1 ao subir o braço.",
    ],
    "mastery": {
        "know": "Sei visualizar o braço inteiro como um mapa contínuo de Am.",
        "play": "Consigo encontrar 1, b3, 4, 5 e b7 em qualquer região.",
        "use": "Consigo improvisar atravessando os cinco shapes sem perder a orientação.",
    },
    "review": ["Shape 1 completo (Aula 2).", "Shape 2 completo (Aula 5).", "Shape 3 completo (Aula 8).", "Shape 4 completo (Aula 11).", "Shape 5: 1, b3 e 5 (Aula 13)."],
    "challenge": "Encontre todas as notas de um único intervalo (ex.: b3) de ponta a ponta do braço em menos de 30 segundos.",
    "mission": "Gravar uma improvisação de 2 minutos atravessando os cinco shapes.",
    "xp": XP,
})

L.append({
    "id": 15, "week": 3, "day": 5, "phase": 1,
    "title": "Boss Battle: avaliação da Fase 1",
    "subtitle": "Randomização, improvisação, conexão e musicalidade nos cinco shapes",
    "objective": "Avaliar o domínio da Fase 1 em quatro partes: randomização shape + intervalo, improvisação em cada shape, conexão entre shapes e musicalidade com chord tones, tensão, resolução, bends, vibrato e silêncio.",
    "prerequisite": "Aulas 1 a 14 concluídas.",
    "concept": "Esta é a prova da Fase 1. Não há conteúdo novo: o objetivo é verificar se você consegue usar — e não apenas memorizar — o mapa de Am. Você deve localizar 1, b3 e 5 nos cinco shapes, localizar 4 e b7 com razoável segurança, identificar intervalos, reconhecer chord tones, terminar frases em chord tones, conectar pelo menos dois shapes sem perder a orientação e usar pelo menos uma relação tensão → resolução. Não exija perfeição: o alvo é Consigo usar.",
    "key": "A minor", "scale": SCALE, "chord": CHORD,
    "cagedForm": "As cinco formas CAGED (E, D, C, A, G) de Am",
    "whatToSee": [
        "Os cinco shapes de Am como um único mapa contínuo.",
        "1, b3 e 5 em cada shape (chord tones).",
        "4 e b7 em cada shape (tensões).",
        "As dobradiças entre shapes consecutivos.",
    ],
    "chordScaleRelation": "O acorde Am (1, b3, 5) é a âncora de todo o braço; as tensões 4 e b7 criam movimento e resolvem de volta ao acorde em qualquer shape.",
    "fretboard": {
        "shape": 1, "position": 5, "highlight": ["1", "b3", "4", "5", "b7"],
        "intervalMap": "e|--1(5)-----b3(8)--\nB|--5(5)-----b7(8)--\nG|--b3(5)----4(7)---\nD|--b7(5)----1(7)---\nA|--4(5)-----5(7)---\nE|--1(5)-----b3(8)--",
        "tab": "e|------------------5-8-|\nB|--------------5-8-----|\nG|----------5-7---------|\nD|------5-7-------------|\nA|--5-7-----------------|\nE|--5-8-----------------|",
    },
    "exercises": [
        "PARTE 1 — Randomização: gere aleatoriamente shape + intervalo (ex.: Shape 1 + b3, Shape 3 + 5, Shape 5 + b7, Shape 2 + 1, Shape 4 + 4) e encontre cada um em menos de 3 segundos.",
        "PARTE 2 — Improvisação: 2 minutos no Shape 1, 2 no Shape 2, 2 no Shape 3, 2 no Shape 4 e 2 no Shape 5, terminando frases em chord tone.",
        "PARTE 3 — Conexão: conectar Shape 1 → 2, Shape 2 → 3, Shape 3 → 4 e Shape 4 → 5 com slides.",
        "PARTE 4 — Musicalidade: improvisar livremente usando chord tones, tensão, resolução, bends, vibrato e silêncio.",
    ],
    "earTraining": {"instruction": "Percorra o braço cantando cada intervalo (1, b3, 4, 5, b7) em diferentes regiões. Depois toque uma nota aleatória e identifique o intervalo antes de olhar."},
    "improvisation": {"instruction": "Improvisação final: 5 minutos livres atravessando os cinco shapes, cumprindo as 7 metas de domínio listadas no critério. Grave e avalie."},
    "theoryRoutine": [
        "00–05 min: Randomização shape + intervalo nos cinco shapes.",
        "05–20 min: Improvisação cronometrada (2 min por shape).",
        "20–27 min: Conexão entre shapes com slides.",
        "27–30 min: Musicalidade livre com gravação para autoavaliação.",
    ],
    "technicalPractice": {
        "duration": "30 minutos",
        "focus": "Resistência e fluência global na Fase 1",
        "routine": [
            "00–08 min: Rodar os cinco shapes em sequência a 60 BPM.",
            "08–18 min: Células de resolução 4 → b3 e b7 → 1 em todos os shapes.",
            "18–26 min: Bend, vibrato e silêncio aplicados às notas de chegada.",
            "26–30 min: Improviso técnico a 80 BPM atravessando o braço.",
        ],
    },
    "backingTrack": BT,
    "video": {"title": "Minor Pentatonic: Essential Information", "channel": "JustinGuitar", "url": "https://www.justinguitar.com/guitar-lessons/minor-pentatonic-essential-information-sc-301", "reason": "Revisão geral dos fundamentos da pentatônica para a avaliação da Fase 1."},
    "commonMistakes": [
        "Memorizar o desenho sem conseguir usar o intervalo conscientemente.",
        "Perder a orientação ao conectar shapes.",
        "Exigir perfeição absoluta em vez de mirar no Consigo usar.",
    ],
    "mastery": {
        "know": "Consigo identificar os intervalos e reconhecer os chord tones nos cinco shapes.",
        "play": "Consigo localizar 1, b3 e 5 nos cinco shapes e 4 e b7 com razoável segurança.",
        "use": "Consigo terminar frases em chord tones, conectar shapes e usar tensão → resolução no improviso.",
    },
    "review": [
        "Localizar 1, b3 e 5 nos cinco shapes.",
        "Localizar 4 e b7 nos cinco shapes.",
        "Terminar frases conscientemente em chord tones.",
        "Conectar pelo menos dois shapes sem perder a orientação.",
        "Usar pelo menos uma relação tensão → resolução.",
    ],
    "challenge": "Grave os 10 minutos completos do Boss Battle e marque, de 1 a 5, seu desempenho em cada uma das 7 metas de domínio.",
    "mission": "Concluir o Boss Battle e registrar sua autoavaliação nas 7 metas de domínio.",
    "xp": XP,
})

data = {"course": course, "lessons": L}
with open("lessons.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("lessons.json gerado com", len(L), "aulas")

